from typing import Any

from sqlalchemy.ext.compiler import compiles
from sqlalchemy.schema import CreateColumn

# Import all the models, so that Base has them before being
# imported by Alembic
from app.db.base_class import Base  # noqa
from app.models.order import Order  # noqa
from app.models.product import Category, Image, Product, Review  # noqa
from app.models.shop import Shop  # noqa
from app.models.users import Users  # noqa


@compiles(CreateColumn, "postgresql")
def use_identity(element: Any, compiler: Any, **kw: dict) -> str:
    text = compiler.visit_create_column(element, **kw)
    return text.replace("SERIAL", "INT GENERATED BY DEFAULT AS IDENTITY")
