class ErrorCode:
    CATEGORY_SLUG_ALREADY_EXISTS = "CATEGORY_SLUG_ALREADY_EXISTS"
    CATEGORY_SLUG_NOT_FOUND = "CATEGORY_SLUG_NOT_FOUND"
    CATEGORY_TITLE_ALREADY_EXISTS = "CATEGORY_TITLE_ALREADY_EXISTS"
